import {Product} from "./Product";

export const products: Product[] = [
    {
        id:1,
        name: "Cake-1",
        price: 30,
        image: "../img/cake-1.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id:2,
        name: "Cake-2",
        price: 30,
        image: "../img/cake-2.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id:3,
        name: "Cake-3",
        price: 50,
        image: "../img/cake-3.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 4,
        name: "CupCake-1",
        price: 50,
        image: "../img/cupcake-1.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 5,
        name: "CupCake-2",
        price: 12,
        image: "../img/cupcake-2.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 6,
        name: "CupCake-3",
        price: 12,
        image: "../img/cupcake-3.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 7,
        name: "Doughnut-1",
        price: 50,
        image: "../img/doughnut-1.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 8,
        name: "Doughnut-2",
        price: 12,
        image: "../img/doughnut-2.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 9,
        name: "Doughnut-3",
        price: 12,
        image: "../img/doughnut-3.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 10,
        name: "Sweets-1",
        price: 50,
        image: "../img/sweets-1.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 11,
        name: "Sweets-2",
        price: 12,
        image: "../img/sweets-2.jpeg",
        description: "test",
        brand: "Dinosaurs",
    },
    {
        id: 12,
        name: "Sweets-3",
        price: 12,
        image: "../img/sweets-3.jpeg",
        description: "test",
        brand: "Dinosaurs",
    }
]